"""empty message

Revision ID: f21d3bdd2213
Revises: 4a3037741d2e
Create Date: 2021-11-16 00:13:17.684152

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f21d3bdd2213'
down_revision = '4a3037741d2e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('todo',
    sa.Column('todo_No', sa.Integer(), nullable=False),
    sa.Column('todo_name', sa.String(length=255), nullable=True, comment='待办名称'),
    sa.Column('todo_desc', sa.String(length=255), nullable=True, comment='待办描述'),
    sa.Column('isfinish', sa.Integer(), nullable=True, comment='是否完成|0=未完成，1=已完成'),
    sa.Column('todo_date', sa.DateTime(), nullable=True, comment='截止时间'),
    sa.PrimaryKeyConstraint('todo_No')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('todo')
    # ### end Alembic commands ###
